import * as Font from "expo-font";
 
export default useFonts = async () =>
  await Font.loadAsync({
    'KottaOne-Regular': require('./../assets/font/KottaOne-Regular.ttf'),
    'Montserrat-Black': require('./../assets/font/Montserrat-Black.ttf'),
    'Montserrat-BlackItalic': require('./../assets/font/Montserrat-BlackItalic.ttf'),
    'Montserrat-Bold': require('./../assets/font/Montserrat-Bold.ttf'),
    'Montserrat-BoldItalic': require('./../assets/font/Montserrat-BoldItalic.ttf'),
    'Montserrat-ExtraBold': require('./../assets/font/Montserrat-ExtraBold.ttf'),
    'Montserrat-ExtraBoldItalic': require('./../assets/font/Montserrat-ExtraBoldItalic.ttf'),
    'Montserrat-ExtraLight': require('./../assets/font/Montserrat-ExtraLight.ttf'),
    'Montserrat-ExtraLightItalic': require('./../assets/font/Montserrat-ExtraLightItalic.ttf'),
    'Montserrat-Italic': require('./../assets/font/Montserrat-Italic.ttf'),
    'Montserrat-Light': require('./../assets/font/Montserrat-Light.ttf'),
    'Montserrat-LightItalic': require('./../assets/font/Montserrat-LightItalic.ttf'),
    'Montserrat-Medium': require('./../assets/font/Montserrat-Medium.ttf'),
    'Montserrat-MediumItalic': require('./../assets/font/Montserrat-MediumItalic.ttf'),
    'Montserrat-Regular': require('./../assets/font/Montserrat-Regular.ttf'),
    'Montserrat-SemiBold': require('./../assets/font/Montserrat-SemiBold.ttf'),
    'Montserrat-SemiBoldItalic': require('./../assets/font/Montserrat-SemiBoldItalic.ttf'),
    'Montserrat-Thin': require('./../assets/font/Montserrat-Thin.ttf'),
    'Montserrat-ThinItalic': require('./../assets/font/Montserrat-ThinItalic.ttf'),
    'Trirong-Black': require('./../assets/font/Trirong-Black.ttf'),
    'Trirong-BlackItalic': require('./../assets/font/Trirong-BlackItalic.ttf'),
    'Trirong-Bold': require('./../assets/font/Trirong-Bold.ttf'),
    'Trirong-BoldItalic': require('./../assets/font/Trirong-BoldItalic.ttf'),
    'Trirong-ExtraBold': require('./../assets/font/Trirong-ExtraBold.ttf'),
    'Trirong-ExtraBoldItalic': require('./../assets/font/Trirong-ExtraBoldItalic.ttf'),
    'Trirong-ExtraLight': require('./../assets/font/Trirong-ExtraLight.ttf'),
    'Trirong-ExtraLightItalic': require('./../assets/font/Trirong-ExtraLightItalic.ttf'),
    'Trirong-Italic': require('./../assets/font/Trirong-Italic.ttf'),
    'Trirong-Light': require('./../assets/font/Trirong-Light.ttf'),
    'Trirong-LightItalic': require('./../assets/font/Trirong-LightItalic.ttf'),
    'Trirong-Medium': require('./../assets/font/Trirong-Medium.ttf'),
    'Trirong-MediumItalic': require('./../assets/font/Trirong-MediumItalic.ttf'),
    'Trirong-Regular': require('./../assets/font/Trirong-Regular.ttf'),
    'Trirong-SemiBold': require('./../assets/font/Trirong-SemiBold.ttf'),
    'Trirong-SemiBoldItalic': require('./../assets/font/Trirong-SemiBoldItalic.ttf'),
    'Trirong-Thin': require('./../assets/font/Trirong-Thin.ttf'),
    'Trirong-ThinItalic': require('./../assets/font/Trirong-ThinItalic.ttf'),
  });